apiVersion: apps/v1
kind: Deployment
metadata:
  name: huma-counter-href-10-sites
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: huma-counter-href-10-sites
  template:
    metadata:
      labels:
        app.kubernetes.io/name: huma-counter-href-10-sites
    spec:
      containers:
      - image: 312910855403.dkr.ecr.eu-west-1.amazonaws.com/huma-counter-href-10-sites:79da2dc
        name: huma-counter-href-10-sites
        ports:
        - containerPort: 8888
