apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-get-href-from-10-websites
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-app-get-href-from-10-websites
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-app-get-href-from-10-websites
    spec:
      containers:
      - image: 312910855403.dkr.ecr.eu-west-1.amazonaws.com/huma-counter-href-10-sites:79da2dc
        name: fastapi-app-get-href-from-10-websites
        ports:
        - containerPort: 8888
