apiVersion: v1
kind: Service
metadata:
  name: huma-counter
  labels:
    app: huma-counter
spec:
  type: ClusterIP
  selector:
    app: huma-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
