apiVersion: apps/v1
kind: Deployment
metadata:
  name: huma-counter
  labels:
    app: huma-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huma-counter
  template:
    metadata:
      labels:
        app: huma-counter
    spec:
      containers:
        - name: huma-container
          image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 8888
